version: '3'
services:
  airflow:
    image: docker-airflow-arm64
    build:
      context: ./docker-airflow-arm64
      dockerfile: Dockerfile.arm64
    restart: always
    volumes:
      - ./airflow-dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - ./containers.txt:/containers.txt
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: webserver
    environment:
      - DOCKER_GROUP_ID=998
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

